# Configurazione del server
server.port=8080

# Configurazione del database
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=tuo_username
spring.datasource.password=tuo_password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configurazione JPA (Java Persistence API)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect

# Configurazione del logging
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG  # Cambia 'com.example' con il pacchetto principale della tua applicazione
