version: "3.8"
services:
  backend-java:
    build:
      context: ./backend-java
    container_name: backendJavaContainer 
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend-go:
    build:
      context: ./backend-go
    container_name: backendGoContainer 
    ports:
      - "8081:8080"
    networks:
      - app-network

  frontend-dart:
    build:
      context: ./frontend-dart
    container_name: frontendDartContainer
    ports:
      - "8082:80"
    volumes:
        - ./frontend-dart:/app #ensures that the local app of dart build is avaiable when setting nginx
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
