name: my_dashboard_frontend
description: frontend_
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"  # Usa una versione SDK compatibile con Dart 2.18

dependencies:
  angular: ^7.0.2

dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.0.0
  matcher: ^0.12.10

executables:
  dart: bin/dart.dart
